[package]
name = "exg-api-gateway"
edition.workspace = true
version.workspace = true

[dependencies]
exg-common = { workspace = true }
exg-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rustc-hash = { workspace = true }
actix-web = { workspace = true }
exg-config = { workspace = true }
exg-user-service = { workspace = true }
sqlx = { workspace = true }
exg-ringbuffer = { workspace = true }
exg-wal = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
rkyv = { workspace = true }
subtle = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
tempfile = { workspace = true }
