[package]
name = "exg-api-gateway"
edition.workspace = true
version.workspace = true

[dependencies]
exg-common = { workspace = true }
exg-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
