[package]
name = "exg-wal"
edition.workspace = true
version.workspace = true

[dependencies]
memmap2 = { workspace = true }
crc32fast = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = "3"

[[bench]]
name = "wal"
harness = false
