[package]
name = "exg-wal"
edition.workspace = true
version.workspace = true

[dependencies]
crc32fast = { workspace = true }
thiserror = { workspace = true }
memmap2 = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }

[[bench]]
name = "wal"
harness = false
