[package]
name = "exg-clearing"
edition.workspace = true
version.workspace = true

[dependencies]
exg-common = { workspace = true }
exg-protocol = { workspace = true }
exg-risk-engine = { workspace = true }
exg-ledger = { workspace = true }
serde = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
