use exg_common::{Decimal128, OrderId, Side, UserId};

use crate::orderbook::{BookOrder, OrderBook};

/// A single fill generated by the matching process.
#[derive(Debug, Clone)]
pub struct Fill {
    pub maker_order_id: OrderId,
    pub taker_order_id: OrderId,
    pub maker_user_id: UserId,
    pub taker_user_id: UserId,
    /// Always at the maker's price (price improvement for taker).
    pub price: Decimal128,
    pub quantity: Decimal128,
    pub taker_side: Side,
}

/// Result of a match attempt.
pub struct MatchResult {
    pub fills: Vec<Fill>,
    /// Whether the order was rejected (e.g. POST_ONLY would take, FOK not fillable).
    pub rejected: bool,
}

/// Match an incoming order against the book.
///
/// Returns fills and whether the order was rejected.
/// The caller is responsible for:
/// - Inserting any remaining quantity onto the book (for resting orders)
/// - Removing fully filled maker orders from the book
///
/// Price-Time Priority:
/// 1. For a BUY order, match against asks (lowest price first)
/// 2. For a SELL order, match against bids (highest price first)
/// 3. At each price level, match in FIFO order
/// 4. Fill at MAKER's price (price improvement for taker)
pub fn match_order(book: &mut OrderBook, order: &mut BookOrder) -> MatchResult {
    use exg_common::TimeInForce;

    // POST_ONLY takes precedence: if order would match, reject it
    if order.time_in_force == TimeInForce::PostOnly {
        let would_match = match order.side {
            Side::Buy => book.best_ask().is_some_and(|ask| order.price >= ask),
            Side::Sell => book.best_bid().is_some_and(|bid| order.price <= bid),
        };
        if would_match {
            return MatchResult {
                fills: Vec::new(),
                rejected: true,
            };
        }
        // Post-only that doesn't cross — will rest on book
        return MatchResult {
            fills: Vec::new(),
            rejected: false,
        };
    }

    // FOK: check if entire quantity can be filled before executing
    if order.time_in_force == TimeInForce::Fok {
        let available = if order.order_type.is_limit() {
            book.available_qty_at_price(order.side, order.price)
        } else {
            // Market FOK — all available depth
            book.total_opposite_qty(order.side)
        };
        if available < order.remaining_qty {
            return MatchResult {
                fills: Vec::new(),
                rejected: true,
            };
        }
    }

    let mut fills = Vec::new();

    // Collect matching price levels and orders
    match order.side {
        Side::Buy => {
            match_against_asks(book, order, &mut fills);
        }
        Side::Sell => {
            match_against_bids(book, order, &mut fills);
        }
    }

    MatchResult {
        fills,
        rejected: false,
    }
}

/// Match a buy order against ask side of the book.
fn match_against_asks(book: &mut OrderBook, taker: &mut BookOrder, fills: &mut Vec<Fill>) {
    // Collect the ask prices to iterate (avoid borrow issues)
    let ask_prices: Vec<Decimal128> = book.ask_levels().map(|l| l.price).collect();

    for ask_price in ask_prices {
        if taker.remaining_qty.is_zero() {
            break;
        }

        // For limit orders, stop if ask price > taker price
        if taker.order_type.is_limit() && ask_price > taker.price {
            break;
        }

        // Get order IDs at this level
        let order_ids: Vec<OrderId> = match book.ask_levels().find(|l| l.price == ask_price) {
            Some(level) => level.orders.clone(),
            None => continue,
        };

        for maker_id in order_ids {
            if taker.remaining_qty.is_zero() {
                break;
            }

            let (maker_user_id, maker_remaining, fill_price) = {
                let maker = match book.get_order(maker_id) {
                    Some(m) => m,
                    None => continue,
                };
                (maker.user_id, maker.remaining_qty, maker.price)
            };

            let fill_qty = taker.remaining_qty.min(maker_remaining);

            fills.push(Fill {
                maker_order_id: maker_id,
                taker_order_id: taker.order_id,
                maker_user_id,
                taker_user_id: taker.user_id,
                price: fill_price,
                quantity: fill_qty,
                taker_side: taker.side,
            });

            taker.remaining_qty = taker.remaining_qty - fill_qty;
            let new_maker_remaining = maker_remaining - fill_qty;

            if new_maker_remaining.is_zero() {
                book.remove_order(maker_id);
            } else {
                book.update_qty(maker_id, new_maker_remaining);
            }
        }
    }
}

/// Match a sell order against bid side of the book.
fn match_against_bids(book: &mut OrderBook, taker: &mut BookOrder, fills: &mut Vec<Fill>) {
    // Collect the bid prices to iterate (avoid borrow issues)
    let bid_prices: Vec<Decimal128> = book.bid_levels().map(|l| l.price).collect();

    for bid_price in bid_prices {
        if taker.remaining_qty.is_zero() {
            break;
        }

        // For limit orders, stop if bid price < taker price
        if taker.order_type.is_limit() && bid_price < taker.price {
            break;
        }

        // Get order IDs at this level
        let order_ids: Vec<OrderId> = match book.bid_levels().find(|l| l.price == bid_price) {
            Some(level) => level.orders.clone(),
            None => continue,
        };

        for maker_id in order_ids {
            if taker.remaining_qty.is_zero() {
                break;
            }

            let (maker_user_id, maker_remaining, fill_price) = {
                let maker = match book.get_order(maker_id) {
                    Some(m) => m,
                    None => continue,
                };
                (maker.user_id, maker.remaining_qty, maker.price)
            };

            let fill_qty = taker.remaining_qty.min(maker_remaining);

            fills.push(Fill {
                maker_order_id: maker_id,
                taker_order_id: taker.order_id,
                maker_user_id,
                taker_user_id: taker.user_id,
                price: fill_price,
                quantity: fill_qty,
                taker_side: taker.side,
            });

            taker.remaining_qty = taker.remaining_qty - fill_qty;
            let new_maker_remaining = maker_remaining - fill_qty;

            if new_maker_remaining.is_zero() {
                book.remove_order(maker_id);
            } else {
                book.update_qty(maker_id, new_maker_remaining);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use exg_common::{OrderType, SymbolId, TimeInForce, UnixMicros};

    fn dec(s: &str) -> Decimal128 {
        s.parse().unwrap()
    }

    fn make_order(
        id: u64,
        user: u64,
        side: Side,
        price: &str,
        qty: &str,
        order_type: OrderType,
        tif: TimeInForce,
    ) -> BookOrder {
        BookOrder {
            order_id: OrderId::new(id),
            user_id: UserId::new(user),
            symbol: SymbolId::new(1),
            side,
            price: dec(price),
            remaining_qty: dec(qty),
            original_qty: dec(qty),
            order_type,
            time_in_force: tif,
            is_reduce_only: false,
            timestamp: UnixMicros::from_micros(1_000_000 + id),
            visible_qty: None,
            hidden_qty: Decimal128::ZERO,
            trailing_delta: None,
            trailing_peak_price: None,
            expire_time: None,
            client_order_id: None,
            stop_price: None,
        }
    }

    fn make_limit(id: u64, user: u64, side: Side, price: &str, qty: &str) -> BookOrder {
        make_order(
            id,
            user,
            side,
            price,
            qty,
            OrderType::Limit,
            TimeInForce::Gtc,
        )
    }

    fn setup_book_with_asks() -> OrderBook {
        let mut book = OrderBook::new(SymbolId::new(1));
        // Asks: 100@51000, 200@52000, 300@53000
        book.insert_order(make_limit(1, 10, Side::Sell, "51000", "100"));
        book.insert_order(make_limit(2, 11, Side::Sell, "52000", "200"));
        book.insert_order(make_limit(3, 12, Side::Sell, "53000", "300"));
        book
    }

    fn setup_book_with_bids() -> OrderBook {
        let mut book = OrderBook::new(SymbolId::new(1));
        // Bids: 300@49000, 200@48000, 100@47000
        book.insert_order(make_limit(1, 10, Side::Buy, "49000", "300"));
        book.insert_order(make_limit(2, 11, Side::Buy, "48000", "200"));
        book.insert_order(make_limit(3, 12, Side::Buy, "47000", "100"));
        book
    }

    // 7. Limit buy matches against ask — single fill
    #[test]
    fn test_limit_buy_single_fill() {
        let mut book = setup_book_with_asks();
        let mut taker = make_limit(100, 20, Side::Buy, "51000", "50");

        let result = match_order(&mut book, &mut taker);

        assert!(!result.rejected);
        assert_eq!(result.fills.len(), 1);
        assert_eq!(result.fills[0].price, dec("51000"));
        assert_eq!(result.fills[0].quantity, dec("50"));
        assert_eq!(result.fills[0].maker_order_id, OrderId::new(1));
        assert_eq!(taker.remaining_qty, Decimal128::ZERO);
    }

    // 8. Limit buy matches multiple price levels
    #[test]
    fn test_limit_buy_multiple_levels() {
        let mut book = setup_book_with_asks();
        // Buy 250 @ 52000 — eats through 51000 (100) and 52000 (150)
        let mut taker = make_limit(100, 20, Side::Buy, "52000", "250");

        let result = match_order(&mut book, &mut taker);

        assert_eq!(result.fills.len(), 2);
        assert_eq!(result.fills[0].price, dec("51000"));
        assert_eq!(result.fills[0].quantity, dec("100"));
        assert_eq!(result.fills[1].price, dec("52000"));
        assert_eq!(result.fills[1].quantity, dec("150"));
        assert_eq!(taker.remaining_qty, Decimal128::ZERO);
    }

    // 9. Market order eats through all available depth
    #[test]
    fn test_market_order_eats_all_depth() {
        let mut book = setup_book_with_asks();
        // Market buy 600 — total available is 100+200+300=600
        let mut taker = make_order(
            100,
            20,
            Side::Buy,
            "0",
            "600",
            OrderType::Market,
            TimeInForce::Ioc,
        );

        let result = match_order(&mut book, &mut taker);

        assert_eq!(result.fills.len(), 3);
        assert_eq!(taker.remaining_qty, Decimal128::ZERO);
        assert!(book.is_empty());
    }

    // 10. POST_ONLY rejected when it would take
    #[test]
    fn test_post_only_rejected_when_would_take() {
        let mut book = setup_book_with_asks();
        let mut taker = make_order(
            100,
            20,
            Side::Buy,
            "51000",
            "10",
            OrderType::Limit,
            TimeInForce::PostOnly,
        );

        let result = match_order(&mut book, &mut taker);

        assert!(result.rejected);
        assert!(result.fills.is_empty());
        // Book unchanged
        assert_eq!(book.order_count(), 3);
    }

    // 11. POST_ONLY accepted when it rests
    #[test]
    fn test_post_only_accepted_when_rests() {
        let mut book = setup_book_with_asks();
        let mut taker = make_order(
            100,
            20,
            Side::Buy,
            "50000",
            "10",
            OrderType::Limit,
            TimeInForce::PostOnly,
        );

        let result = match_order(&mut book, &mut taker);

        assert!(!result.rejected);
        assert!(result.fills.is_empty());
    }

    // 12. IOC partial fill — remaining canceled
    #[test]
    fn test_ioc_partial_fill() {
        let mut book = setup_book_with_asks();
        // IOC buy 150 @ 51000 — only 100 available at that price
        let mut taker = make_order(
            100,
            20,
            Side::Buy,
            "51000",
            "150",
            OrderType::Limit,
            TimeInForce::Ioc,
        );

        let result = match_order(&mut book, &mut taker);

        assert!(!result.rejected);
        assert_eq!(result.fills.len(), 1);
        assert_eq!(result.fills[0].quantity, dec("100"));
        // Remaining 50 should be left on taker (caller cancels it for IOC)
        assert_eq!(taker.remaining_qty, dec("50"));
    }

    // 13. FOK full fill succeeds
    #[test]
    fn test_fok_full_fill() {
        let mut book = setup_book_with_asks();
        // FOK buy 100 @ 51000 — exactly available
        let mut taker = make_order(
            100,
            20,
            Side::Buy,
            "51000",
            "100",
            OrderType::Limit,
            TimeInForce::Fok,
        );

        let result = match_order(&mut book, &mut taker);

        assert!(!result.rejected);
        assert_eq!(result.fills.len(), 1);
        assert_eq!(result.fills[0].quantity, dec("100"));
        assert_eq!(taker.remaining_qty, Decimal128::ZERO);
    }

    // 14. FOK insufficient depth — rejected entirely
    #[test]
    fn test_fok_insufficient_depth() {
        let mut book = setup_book_with_asks();
        // FOK buy 150 @ 51000 — only 100 available
        let mut taker = make_order(
            100,
            20,
            Side::Buy,
            "51000",
            "150",
            OrderType::Limit,
            TimeInForce::Fok,
        );

        let result = match_order(&mut book, &mut taker);

        assert!(result.rejected);
        assert!(result.fills.is_empty());
        // Book unchanged
        assert_eq!(book.order_count(), 3);
    }

    // 15. ICEBERG: visible portion filled, refills from hidden
    #[test]
    fn test_iceberg_refill() {
        let mut book = OrderBook::new(SymbolId::new(1));
        // Place iceberg bid: visible=10, total=30
        let iceberg = BookOrder {
            order_id: OrderId::new(1),
            user_id: UserId::new(10),
            symbol: SymbolId::new(1),
            side: Side::Buy,
            price: dec("50000"),
            remaining_qty: dec("10"), // visible portion on book
            original_qty: dec("30"),
            order_type: OrderType::Iceberg,
            time_in_force: TimeInForce::Gtc,
            is_reduce_only: false,
            timestamp: UnixMicros::from_micros(1_000_000),
            visible_qty: Some(dec("10")),
            hidden_qty: dec("20"), // hidden remainder
            trailing_delta: None,
            trailing_peak_price: None,
            expire_time: None,
            client_order_id: None,
            stop_price: None,
        };
        book.insert_order(iceberg);

        // Sell 10 @ 50000 — fills visible portion
        let mut taker = make_limit(100, 20, Side::Sell, "50000", "10");
        let result = match_order(&mut book, &mut taker);

        assert_eq!(result.fills.len(), 1);
        assert_eq!(result.fills[0].quantity, dec("10"));

        // The iceberg was fully consumed from the book
        // Engine would handle refill — here we verify the maker was removed
        assert!(book.get_order(OrderId::new(1)).is_none());
    }

    // 16. Price-time priority: same price, earlier order fills first
    #[test]
    fn test_price_time_priority() {
        let mut book = OrderBook::new(SymbolId::new(1));
        // Two asks at same price, order 1 first, order 2 second
        book.insert_order(make_limit(1, 10, Side::Sell, "51000", "5"));
        book.insert_order(make_limit(2, 11, Side::Sell, "51000", "5"));

        let mut taker = make_limit(100, 20, Side::Buy, "51000", "3");
        let result = match_order(&mut book, &mut taker);

        assert_eq!(result.fills.len(), 1);
        // Should fill against order 1 first (FIFO)
        assert_eq!(result.fills[0].maker_order_id, OrderId::new(1));
        assert_eq!(result.fills[0].quantity, dec("3"));
    }

    // 17. Price improvement: taker gets maker's better price
    #[test]
    fn test_price_improvement() {
        let mut book = OrderBook::new(SymbolId::new(1));
        // Ask at 50000
        book.insert_order(make_limit(1, 10, Side::Sell, "50000", "10"));

        // Buy at 51000 — should fill at 50000 (maker's price)
        let mut taker = make_limit(100, 20, Side::Buy, "51000", "5");
        let result = match_order(&mut book, &mut taker);

        assert_eq!(result.fills.len(), 1);
        assert_eq!(result.fills[0].price, dec("50000")); // maker's price, not taker's
    }

    // Sell side tests
    #[test]
    fn test_sell_matches_bids() {
        let mut book = setup_book_with_bids();
        // Sell 400 @ 48000 — fills 300@49000 + 100@48000
        let mut taker = make_limit(100, 20, Side::Sell, "48000", "400");
        let result = match_order(&mut book, &mut taker);

        assert_eq!(result.fills.len(), 2);
        assert_eq!(result.fills[0].price, dec("49000"));
        assert_eq!(result.fills[0].quantity, dec("300"));
        assert_eq!(result.fills[1].price, dec("48000"));
        assert_eq!(result.fills[1].quantity, dec("100"));
        assert_eq!(taker.remaining_qty, Decimal128::ZERO);
    }

    #[test]
    fn test_post_only_sell_rejected() {
        let mut book = setup_book_with_bids();
        let mut taker = make_order(
            100,
            20,
            Side::Sell,
            "49000",
            "10",
            OrderType::Limit,
            TimeInForce::PostOnly,
        );
        let result = match_order(&mut book, &mut taker);
        assert!(result.rejected);
    }

    #[test]
    fn test_fok_sell_success() {
        let mut book = setup_book_with_bids();
        // FOK sell 300 @ 49000
        let mut taker = make_order(
            100,
            20,
            Side::Sell,
            "49000",
            "300",
            OrderType::Limit,
            TimeInForce::Fok,
        );
        let result = match_order(&mut book, &mut taker);
        assert!(!result.rejected);
        assert_eq!(result.fills.len(), 1);
        assert_eq!(result.fills[0].quantity, dec("300"));
    }
}
